version: '2'
services:
  app_demo-app:
    image: app_demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mariadb://172.16.29.128:3306/app_demo
      - JHIPSTER_CACHE_REDIS_SERVER=redis://172.16.29.128:8081
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://app_demo-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://app_demo-elasticsearch:9200
    ports:
      - 8080:8080
  app_demo-mariadb:
    extends:
      file: mariadb.yml
      service: app_demo-mariadb
  app_demo-redis:
    extends:
      file: redis.yml
      service: app_demo-redis
  app_demo-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: app_demo-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
